---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{gaia_user}}"
        password: "{{gaia_password}}"
        management: "{{server_management_ip}}"
      context: "gaia_api"
      api_version: 1.1
      fingerprint: "C3:B4:54:8D:0E:C0:7E:D4:31:64:94:13:F5:14:CD:93:68:6A:4F:4D"
    register: login_response

  - name: "set physical interface"
    check_point_mgmt:
      command: set-physical-interface
      parameters:
        name: "eth2"
        enabled: "true"
      session-data: "{{ login_response }}"

  - name: "show syslog"
    check_point_mgmt:
      command: show-syslog
      api_version: 1                          #This is an example of overwriting the version determined on login
      session-data: "{{ login_response }}"

  - name: "show asset"
    check_point_mgmt:
      command: show-asset
      session-data: "{{ login_response }}"
