---
- hosts: GW1
  connection: local
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{inventory_hostname}}"
        context: "gaia_api"
      fingerprint: "{{hostvars[inventory_hostname]['fingerprint']}}"
    register: login_response

  - name: "show vrrp summary"
    check_point_mgmt:
      command: show-vrrp-summary
      parameters:
        context: "gaia_api"
      session-data: "{{ login_response }}"

  - name: "set physical interface"
    check_point_mgmt:
      command: set-physical-interface
      parameters:
        name: "eth2"
        enabled: "true"
        context: "gaia_api"        
      session-data: "{{ login_response }}"
      
  - name: "show asset"
    check_point_mgmt:
      command: show-asset
      parameters:
        context: "gaia_api"        
      session-data: "{{ login_response }}"
