---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{gaia_user}}"
        password: "{{gaia_password}}"
        management: "{{server_management_ip}}"
      context: "gaia_api"
      api_version: 1.1
      fingerprint: "8438E4D59ECAA394D91A6A0CF341D7C01D2E9836"
    register: login_response

  - name: "set physical interface"
    check_point_mgmt:
      command: set-physical-interface
      parameters:
        name: "eth2"
        enabled: "true"
      session-data: "{{ login_response }}"

  - name: "show syslog"
    check_point_mgmt:
      command: show-syslog
      session-data: "{{ login_response }}"

  - name: "show asset"
    check_point_mgmt:
      command: show-asset
      session-data: "{{ login_response }}"
