---
- hosts: "localhost"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{gaia_user}}"
        password: "{{gaia_password}}"
        management: "{{gaia_server}}"
      context: "gaia_api"
      fingerprint: "8438E4D59ECAA394D91A6A0CF341D7C01D2E9836"
    register: login_response

  - name: "set physical interface"
    check_point_mgmt:
      command: set-physical-interface
      parameters:
        name: "eth2"
        enabled: "true"
      context: "gaia_api"
      session-data: "{{ login_response }}"

  - name: "show remote syslog"
    check_point_mgmt:
      command: show-remote-syslog
      parameters:
        server-ip: "192.168.1.2"
      context: "gaia_api"
      session-data: "{{ login_response }}"

  - name: "show asset"
    check_point_mgmt:
      command: show-asset
      context: "gaia_api"
      session-data: "{{ login_response }}"
